### ISSUE TITLE
pre-create the projects

### ISSUE THREAD

**Issue by erwangranger** [rh-aiservices-bu/insurance-claim-processing#150]
for each user (user1 - userX):
- create a project called "userX-auto"
- ensure userX is admin of that project
- deploy minio
- deploy the DS pipeline server
- create a workbench 
- git clone the project 

then 
* adjust instructions/code to match
* keep the instructions where people create their own artifacts, but instead call it "userX-diy"

**Comment by RHRolun** [comment]
@erwangranger is there any benefit of deploying minio in each rather than using the shared minio?
I'm asking cause I have to call the data connection "Shared Minio - pipelines" even for the automatically created users (with their own minio) with their own minio so that the secret looks the same for the pipelines.

**Comment by erwangranger** [comment]
I can't think of any major benefit. 1 minio with 60 buckets, vs 60 minio with one bucket. Results are mostly the same, but with a lot more pods. 

The shared minio has been solid for us, so we could keep that part unchanged. 
Also, if users were doing this "the long way", manually, we'd need to provide them instructions for Minio as well. 

I'd say, for now, we can limit it to just creating the Data Connection to the shared minio, and keep a single Minio. I'm ok with that.

**Comment by RHRolun** [comment]
Closed with https://github.com/rh-aiservices-bu/insurance-claim-processing/pull/181
